frequency: 100
sensor_timeout: 0.4
two_d_mode: true
      
publish_tf: true
        
odom_frame: odom            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: odom           # Defaults to the value of odom_frame if unspecified
      
print_diagnostics: true

odom0: /odom_wheels        # wheels     -> 100 Hz
imu0:  /rtabmap/imu_cov    # camera imu -> 200 Hz

#  X,        Y,      Z,
#  roll,     pitch,  yaw,
#  X/dt,     Y/dt,   Z/dt,
#  roll/dt,  pitch/dt,yaw/dt,
#  X/dt2,    Y/dt2,  Z/dt2 

# in the frame_id of the input message 
odom0_config: [false, false, false, 
               false, false, false, 
               true,  true,  false, 
               false, false, true, 
               false, false, false]
               
imu0_config: [false, false, false, 
               false, false, false, 
               false, false, false, 
               false, true,  false, # select the giroscope along gravity
               false, false, false] # use the x acceleration? But it is non zero due to orientation

# if more than 1 source gives "absolute data (position/orientation)", then put just 1 and the others in differential=true mode
                                   
odom0_queue_size: 4
imu0_queue_size:  8

imu0_angular_velocity_rejection_threshold: 2 # in Mahalanobis distance! sqrt(0.2*0.2*100) 
                                             # max vel is 0.5, cov = 1e-2, dev_st = 0.1, if 
                                             # we consider 2*dev_st=0.2, we discard 5% of measures

# process_noise_covariance: 
# In general, the larger the value for Q relative to the variance for a given variable in an input message, the faster the filter will converge to the value in the measurement.

process_noise_covariance: [1e-6, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    1e-6, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    1e-6, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    1e-6, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    1e-6, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    1e-6, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                           
                           0,    0,    0,    0,    0,    0,    1e-4,  0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     1e-4,  0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     1e-4, 0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    1e-4, 0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    1e-4, 0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    2e-2, 0,    0,    0,
                           
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    1e-6, 0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    1e-6, 0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    1e-6]
