frequency: 5
sensor_timeout: 0.4
two_d_mode: true
      
publish_tf: true
        
odom_frame: odom            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: odom           # Defaults to the value of odom_frame if unspecified
      
print_diagnostics: true

twist0: /twist_n_covariance_wheels
odom0: /rtabmap/odom

#  X,        Y,      Z,
#  roll,     pitch,  yaw,
#  X/dt,     Y/dt,   Z/dt,
#  roll/dt,  pitch/dt,yaw/dt,
#  X/dt2,    Y/dt2,  Z/dt2 

twist0_config: [false, false, false, # wheels
               false, false, false, 
               true,  true,  false, 
               false, false, true, 
               false, false, false]

odom0_config: [false, false, false, # wheels
               false, false, true, 
               true,  true,  false, 
               false, false, false, 
               false, false, false]

smooth_lagged_data: false 
  
odom0_queue_size: 20                                  
twist0_queue_size: 20

odom0_twist_rejection_threshold: 1.5

#imu1_queue_size: 50
#imu0_differential: true
#imu1_differential: false

#imu0_relative: false
#imu1_relative: false
      
twist0_twist_rejection_threshold: 1.5

