global_frame: map
robot_base_frame: base_link
update_frequency: 1
publish_frequency: 1
plugins:

   - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
   
   
inflation_layer:
  inflation_radius: 0.9 # 2xfootprint, it helps to keep the global planned path farther from obstacles

